name: run-jmeter-scripts

on:
 workflow_call:
   inputs:
      testFilePath:    
        required: true
        type: string
        default: 'tests/'
      outputsReportFolder:    
        required: false
        type: string
        default: 'reports'
      jmeterVersion:
        required: true
        type: string
        default: '5.3'
      jmeterArgs:
        required: false
        type: string
      loadtestgitrepobranch:
        required: true
        type: string
      loadtestgitrepo:
        required: true
        type: string 
      javaVersion:
        required: false
        type: string
        default: 11
      analyzeResults:
        required: false
        type: string
        default: 'FALSE'
      use-jpgc-casutg:
        required: false
        type: string
        default: "false"
   # secrets:  
   #    PERSONAL_ACCESS_TOKEN:
   #      required: true

                    
jobs:
  run-jmeter-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the central repo
        uses: actions/checkout@v2
        with:
         ref: '${{ inputs.loadtestgitrepobranch }}'
         repository: '${{ inputs.loadtestgitrepo }}'
        #  token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      # - name: List files in the workspace
      #   run: |
      #    ls -R /github/workspace
      # - name: Debug root dir
      #   run: ls -R /
      # - name: Debug dir n central-repo
      #   run: ls -R GHADemo_Central_Repo
      - name: Set up JDK ${{ inputs.javaVersion }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.javaVersion }}
          overwrite-settings: false
          distribution: 'adopt'
      - name: Run JMeter Tests with plugin
        if: ${{ inputs.use-jpgc-casutg }} == "true"
        uses: rbhadti94/apache-jmeter-action@v0.6.0
        with:
          testFilePath: ${{ inputs.testFilePath }}
          outputReportsFolder: ${{ inputs.outputsReportFolder }}
          args: ${{ inputs.jmeterArgs }}
      - name: Run JMeter Tests
        if: ${{ inputs.use-jpgc-casutg }} == "false"
        uses: rbhadti94/apache-jmeter-action@v0.6.0
        with:
          testFilePath: ${{ inputs.testFilePath }}
          outputReportsFolder: ${{ inputs.outputsReportFolder }}
          args: ${{ inputs.jmeterArgs }}
      # - name: Create virtual environment
      #   run: python -m venv venv
      # - name: Install Python script dependencies
      #   run: source venv/bin/activate; pip3 install -r requirements.txt
      # - name: "[[ALBERTSONS]]: Generate Formatted HTML Report"
      #   env:
      #     ANALYZE_RESULTS: 'FALSE'
      #   run: source venv/bin/activate; python3 -u report_generator.py      
      # - name: Arhive the Report Artifacts
      #   if: always()
      #   run: |
      #     ls -al
      #     tar -czvf ${{ github.event.repository.name }}.tar.gz  -C ${{ github.workspace }} reports/
      # - name: Upload Results
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: jmeter-results
      #     path: |
      #       ${{ inputs.outputsReportFolder }}/*
      #       **/*.tar.gz
      #       report.html
      # - name: "[[ALBERTSONS]]: Analyze Results"
      #   if: ( inputs.analyzeResults == 'TRUE' )
      #   env:
      #     ANALYZE_RESULTS: 'TRUE'
      #   run: |
      #      source venv/bin/activate
      #      python3 -u report_generator.py 
      # - name: Generate Summary
      #   if: always()
      #   run: |
      #     echo '## Build Summary :rocket:' >> $GITHUB_STEP_SUMMARY
      #     echo '+ Application Repository: ${{ github.repository	 }} :book:' >> $GITHUB_STEP_SUMMARY
      #     echo '+ Current Branch: ${{ github.ref_name }} :palm_tree:' >> $GITHUB_STEP_SUMMARY 
